// <auto-generated />
namespace MVC4LOL.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class typo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(typo));
        
        string IMigrationMetadata.Id
        {
            get { return "201302141252259_typo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
