// <auto-generated />
namespace MVC4LOL.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class rename : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(rename));
        
        string IMigrationMetadata.Id
        {
            get { return "201305160957431_rename"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
