// <auto-generated />
namespace MVC4LOL.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class itemImage : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(itemImage));
        
        string IMigrationMetadata.Id
        {
            get { return "201305061250119_itemImage"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
