// <auto-generated />
namespace MVC4LOL.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ChampionDataNoTag : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ChampionDataNoTag));
        
        string IMigrationMetadata.Id
        {
            get { return "201302141356463_ChampionDataNoTag"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
